# docker-compose.yml
version: "3.7"
services:
  collector:
    image: mths/datenstrom-collector
    restart: always
    tty: true
    ports:
      - 8000:8000
    environment:
      - RECORD_FORMAT=avro
      - TRANSPORT=sqs
      - SQS_QUEUE_RAW=datenstrom_raw
      - SQS_QUEUE_EVENTS=datenstrom_events
      - SQS_QUEUE_ERRORS=datenstrom_errors
      - 'IGLU_SCHEMA_REGISTRIES=["http://iglucentral.com/schemas/"]'
      - GEOIP_ENABLED=true
      - AWS_DEFAULT_REGION=eu-central-1
      - 'DOMAIN_CHECK_REGEX=.*[.]datenstrom[.]io'

  enricher:
    image: mths/datenstrom-enricher
    restart: always
    tty: true
    environment:
      - RECORD_FORMAT=avro
      - TRANSPORT=sqs
      - SQS_QUEUE_RAW=datenstrom_raw
      - SQS_QUEUE_EVENTS=datenstrom_events
      - SQS_QUEUE_ERRORS=datenstrom_errors
      - 'IGLU_SCHEMA_REGISTRIES=["http://iglucentral.com/schemas/"]'
      - GEOIP_ENABLED=true
      - AWS_DEFAULT_REGION=eu-central-1
