# docker-compose.yml
version: "3.7"
services:

  collector:
    image: mths/datenstrom-collector
    restart: always
    tty: true
    ports:
      - 8000:8000
    environment:
      - RECORD_FORMAT=avro
      - SINK=kafka
      - KAFKA_BROKERS=kafka:9092
      - IGLU_SCHEMA_REGISTRIES=["http://iglucentral.com/schemas/"]
      - KAFKA_TOPIC_RAW=datenstrom_raw
      - KAFKA_TOPIC_EVENTS=datenstrom_events
      - KAFKA_TOPIC_ERRORS=datenstrom_errors
    depends_on:
      - kafka

  enricher:
    image: mths/datenstrom-enricher
    restart: always
    tty: true
    environment:
      - RECORD_FORMAT=avro
      - SINK=kafka
      - KAFKA_BROKERS=kafka:9092
      - IGLU_SCHEMA_REGISTRIES=["http://iglucentral.com/schemas/"]
      - KAFKA_TOPIC_RAW=datenstrom_raw
      - KAFKA_TOPIC_EVENTS=datenstrom_events
      - KAFKA_TOPIC_ERRORS=datenstrom_errors
    depends_on:
      - kafka

  zookeeper:
    restart: always
    image: docker.io/bitnami/zookeeper:3.9
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper-volume:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    restart: always
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9093:9093"
    volumes:
      - "kafka-volume:/bitnami"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

volumes:
  kafka-volume:
  zookeeper-volume:
